<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>MeuPonto</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ReqnrollObsoleteCodeBehindFiles Remove="Features\AberturaContrato - Copy.feature.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="8.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.7" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.10.0" />
    <PackageReference Include="Reqnroll.xUnit" Version="2.0.2" />
    <PackageReference Include="xunit" Version="2.8.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.1" />
    <PackageReference Include="FluentAssertions" Version="6.12.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Drivers\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\MeuPonto.Web\MeuPonto.Web.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Features\EncerramentoContrato.feature.cs">
      <DependentUpon>EncerramentoContrato.feature</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <ReqnrollFeatureFiles Update="Features\EncerramentoContrato.feature">
      <Visible>$(UsingMicrosoftNETSdk)</Visible>
      <CodeBehindFile>%(RelativeDir)%(Filename).feature$(DefaultLanguageSourceExtension)</CodeBehindFile>
    </ReqnrollFeatureFiles>
  </ItemGroup>

</Project>
