// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace MeuPonto.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class GestaoContratosFeature : object, Xunit.IClassFixture<GestaoContratosFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "GestaoContratos.feature"
#line hidden
        
        public GestaoContratosFeature(GestaoContratosFeature.FixtureData fixtureData, MeuPonto_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-br"), "Features", "Gestão Contratos", "O sistema deverá fornecer para o trabalhador a capacidade de gerenciar seus contr" +
                    "atos.", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="[Abrir Contrato] Trabalhador abre um contrato")]
        [Xunit.TraitAttribute("FeatureTitle", "Gestão Contratos")]
        [Xunit.TraitAttribute("Description", "[Abrir Contrato] Trabalhador abre um contrato")]
        [Xunit.TraitAttribute("Category", "main")]
        [Xunit.TraitAttribute("Category", "wip")]
        public void AbrirContratoTrabalhadorAbreUmContrato()
        {
            string[] tagsOfScenario = new string[] {
                    "main",
                    "wip"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("[Abrir Contrato] Trabalhador abre um contrato", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 10
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 11
 testRunner.When("o trabalhador solicitar a abertura de um contrato", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 12
 testRunner.Then("o sistema deverá apresentar um contrato novo", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 13
 testRunner.And("o contrato deverá ser ativo", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
                TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                            "dia semana",
                            "tempo"});
                table8.AddRow(new string[] {
                            "Sunday",
                            "00:00:00"});
                table8.AddRow(new string[] {
                            "Monday",
                            "08:00:00"});
                table8.AddRow(new string[] {
                            "Tuesday",
                            "08:00:00"});
                table8.AddRow(new string[] {
                            "Wednesday",
                            "08:00:00"});
                table8.AddRow(new string[] {
                            "Thursday",
                            "08:00:00"});
                table8.AddRow(new string[] {
                            "Friday",
                            "08:00:00"});
                table8.AddRow(new string[] {
                            "Saturday",
                            "00:00:00"});
#line 14
 testRunner.And("o contrato deverá prever a seguinte jornada de trabalho semanal:", ((string)(null)), table8, "E ");
#line hidden
                TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                            "nome",
                            "ativo",
                            "domingo",
                            "segunda",
                            "terça",
                            "quarta",
                            "quinta",
                            "sexta",
                            "sábado"});
                table9.AddRow(new string[] {
                            "Contrato A",
                            "True",
                            "00:00:00",
                            "08:00:00",
                            "08:00:00",
                            "08:00:00",
                            "08:00:00",
                            "08:00:00",
                            "00:00:00"});
#line 23
 testRunner.When("o trabalhador abrir o contrato como:", ((string)(null)), table9, "Quando ");
#line hidden
#line 26
 testRunner.Then("o sistema deverá registrar o contrato como esperado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="[Alterar Contrato] Trabalhador altera um contrato para corrigir um erro de digita" +
            "ção no nome")]
        [Xunit.TraitAttribute("FeatureTitle", "Gestão Contratos")]
        [Xunit.TraitAttribute("Description", "[Alterar Contrato] Trabalhador altera um contrato para corrigir um erro de digita" +
            "ção no nome")]
        [Xunit.TraitAttribute("Category", "main")]
        public void AlterarContratoTrabalhadorAlteraUmContratoParaCorrigirUmErroDeDigitacaoNoNome()
        {
            string[] tagsOfScenario = new string[] {
                    "main"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("[Alterar Contrato] Trabalhador altera um contrato para corrigir um erro de digita" +
                    "ção no nome", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 31
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 32
 testRunner.Given("que existe um contrato aberto \'Marcello - Particular\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 33
 testRunner.When("o trabalhador iniciar uma edição de contrato", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
                TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                            "nome"});
                table10.AddRow(new string[] {
                            "Marcelo - Particular"});
#line 34
 testRunner.And("o trabalhador alterar esse contrato para", ((string)(null)), table10, "E ");
#line hidden
#line 37
 testRunner.Then("o nome do contrato deverá ser \'Marcelo - Particular\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="[Abrir Contrato] Trabalhador abre um contrato com nome maior que 2 caractere")]
        [Xunit.TraitAttribute("FeatureTitle", "Gestão Contratos")]
        [Xunit.TraitAttribute("Description", "[Abrir Contrato] Trabalhador abre um contrato com nome maior que 2 caractere")]
        [Xunit.TraitAttribute("Category", "secondary")]
        public void AbrirContratoTrabalhadorAbreUmContratoComNomeMaiorQue2Caractere()
        {
            string[] tagsOfScenario = new string[] {
                    "secondary"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("[Abrir Contrato] Trabalhador abre um contrato com nome maior que 2 caractere", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 42
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 43
 testRunner.Given("que existe uma abertura de contrato em andamento", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
                TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                            "nome"});
                table11.AddRow(new string[] {
                            "Contrato B"});
#line 44
 testRunner.When("o trabalhador abrir o contrato como:", ((string)(null)), table11, "Quando ");
#line hidden
#line 47
 testRunner.Then("o sistema deverá registrar o contrato como esperado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="[Alterar Contrato] Trabalhador altera um contrato com nome maior que 2 caractere")]
        [Xunit.TraitAttribute("FeatureTitle", "Gestão Contratos")]
        [Xunit.TraitAttribute("Description", "[Alterar Contrato] Trabalhador altera um contrato com nome maior que 2 caractere")]
        [Xunit.TraitAttribute("Category", "secondary")]
        public void AlterarContratoTrabalhadorAlteraUmContratoComNomeMaiorQue2Caractere()
        {
            string[] tagsOfScenario = new string[] {
                    "secondary"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("[Alterar Contrato] Trabalhador altera um contrato com nome maior que 2 caractere", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 50
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 51
 testRunner.Given("que existe um contrato aberto \'Contrato Feito\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 52
 testRunner.And("que existe uma edição desse contrato em andamento \'Contrato Feito\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
                TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                            "nome"});
                table12.AddRow(new string[] {
                            "Contrato B"});
#line 53
 testRunner.When("o trabalhador alterar esse contrato para", ((string)(null)), table12, "Quando ");
#line hidden
#line 56
 testRunner.Then("o sistema deverá alterar o contrato como esperado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="[Abrir Contrato] Trabalhador tenta abrir um contrato com nome menor que 3 caracte" +
            "res")]
        [Xunit.TraitAttribute("FeatureTitle", "Gestão Contratos")]
        [Xunit.TraitAttribute("Description", "[Abrir Contrato] Trabalhador tenta abrir um contrato com nome menor que 3 caracte" +
            "res")]
        [Xunit.TraitAttribute("Category", "exception")]
        public void AbrirContratoTrabalhadorTentaAbrirUmContratoComNomeMenorQue3Caracteres()
        {
            string[] tagsOfScenario = new string[] {
                    "exception"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("[Abrir Contrato] Trabalhador tenta abrir um contrato com nome menor que 3 caracte" +
                    "res", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 59
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 60
 testRunner.Given("que existe uma abertura de contrato em andamento", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
                TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                            "nome"});
                table13.AddRow(new string[] {
                            "A"});
#line 61
 testRunner.When("o trabalhador tentar abrir um contrato como", ((string)(null)), table13, "Quando ");
#line hidden
#line 64
 testRunner.Then("a tentativa de abrir o contrato deverá falhar com um erro \"\'Nome\' deve ser maior " +
                        "ou igual a 3 caracteres.\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="[Alterar Contrato] Trabalhador tenta alterar um contrato com nome menor que 3 car" +
            "acteres")]
        [Xunit.TraitAttribute("FeatureTitle", "Gestão Contratos")]
        [Xunit.TraitAttribute("Description", "[Alterar Contrato] Trabalhador tenta alterar um contrato com nome menor que 3 car" +
            "acteres")]
        [Xunit.TraitAttribute("Category", "exception")]
        public void AlterarContratoTrabalhadorTentaAlterarUmContratoComNomeMenorQue3Caracteres()
        {
            string[] tagsOfScenario = new string[] {
                    "exception"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("[Alterar Contrato] Trabalhador tenta alterar um contrato com nome menor que 3 car" +
                    "acteres", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 67
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 68
 testRunner.Given("que existe um contrato aberto \'Contrato Feito\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 69
 testRunner.And("que existe uma edição desse contrato em andamento \'Contrato Feito\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
                TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                            "nome"});
                table14.AddRow(new string[] {
                            "B"});
#line 70
 testRunner.When("o trabalhador tentar alterar esse contrato para", ((string)(null)), table14, "Quando ");
#line hidden
#line 73
 testRunner.Then("a tentativa de alterar o contrato deverá falhar com um erro \"\'Nome\' deve ser maio" +
                        "r ou igual a 3 caracteres.\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="[Abrir Contrato] Trabalhador abre um contrato com nome menor que 36 caracteres")]
        [Xunit.TraitAttribute("FeatureTitle", "Gestão Contratos")]
        [Xunit.TraitAttribute("Description", "[Abrir Contrato] Trabalhador abre um contrato com nome menor que 36 caracteres")]
        [Xunit.TraitAttribute("Category", "secondary")]
        public void AbrirContratoTrabalhadorAbreUmContratoComNomeMenorQue36Caracteres()
        {
            string[] tagsOfScenario = new string[] {
                    "secondary"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("[Abrir Contrato] Trabalhador abre um contrato com nome menor que 36 caracteres", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 78
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 79
 testRunner.Given("que existe uma abertura de contrato em andamento", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
                TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                            "nome"});
                table15.AddRow(new string[] {
                            "Contrato B"});
#line 80
 testRunner.When("o trabalhador abrir o contrato como:", ((string)(null)), table15, "Quando ");
#line hidden
#line 83
 testRunner.Then("o sistema deverá registrar o contrato como esperado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="[Abrir Contrato] Trabalhador tenta abrir um contrato com nome maior que 35 caract" +
            "eres")]
        [Xunit.TraitAttribute("FeatureTitle", "Gestão Contratos")]
        [Xunit.TraitAttribute("Description", "[Abrir Contrato] Trabalhador tenta abrir um contrato com nome maior que 35 caract" +
            "eres")]
        [Xunit.TraitAttribute("Category", "exception")]
        public void AbrirContratoTrabalhadorTentaAbrirUmContratoComNomeMaiorQue35Caracteres()
        {
            string[] tagsOfScenario = new string[] {
                    "exception"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("[Abrir Contrato] Trabalhador tenta abrir um contrato com nome maior que 35 caract" +
                    "eres", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 86
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 87
 testRunner.Given("que existe uma abertura de contrato em andamento", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
                TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                            "nome"});
                table16.AddRow(new string[] {
                            "Contrato de Trabalho Feito com uma Empresa do Ramo da Industria Farmacêutica do E" +
                                "stado do Rio de Janeiro"});
#line 88
 testRunner.When("o trabalhador tentar abrir um contrato como", ((string)(null)), table16, "Quando ");
#line hidden
#line 91
 testRunner.Then("a tentativa de abrir o contrato deverá falhar com um erro \"\'Nome\' deve ser menor " +
                        "ou igual a 35 caracteres.\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="[Abrir Contrato] Trabalhador abre um contrato com uma jornada de trabalho previst" +
            "a de 40 horas semanais")]
        [Xunit.TraitAttribute("FeatureTitle", "Gestão Contratos")]
        [Xunit.TraitAttribute("Description", "[Abrir Contrato] Trabalhador abre um contrato com uma jornada de trabalho previst" +
            "a de 40 horas semanais")]
        [Xunit.TraitAttribute("Category", "secondary")]
        public void AbrirContratoTrabalhadorAbreUmContratoComUmaJornadaDeTrabalhoPrevistaDe40HorasSemanais()
        {
            string[] tagsOfScenario = new string[] {
                    "secondary"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("[Abrir Contrato] Trabalhador abre um contrato com uma jornada de trabalho previst" +
                    "a de 40 horas semanais", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 96
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 97
 testRunner.Given("que existe uma abertura de contrato em andamento", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 98
 testRunner.And("que a jornada de trabalho semanal é de \'Monday\' a \'Friday\' das \'09:00\' às \'18:00\'" +
                        " com \'01:00\' de almoço", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 99
 testRunner.But("que não tem jornada de trabalho no \'Saturday\' e no \'Sunday\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Mas ");
#line hidden
#line 100
 testRunner.When("o trabalhador abrir um contrato", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
                TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                            "dia semana",
                            "tempo"});
                table17.AddRow(new string[] {
                            "Sunday",
                            "00:00:00"});
                table17.AddRow(new string[] {
                            "Monday",
                            "08:00:00"});
                table17.AddRow(new string[] {
                            "Tuesday",
                            "08:00:00"});
                table17.AddRow(new string[] {
                            "Wednesday",
                            "08:00:00"});
                table17.AddRow(new string[] {
                            "Thursday",
                            "08:00:00"});
                table17.AddRow(new string[] {
                            "Friday",
                            "08:00:00"});
                table17.AddRow(new string[] {
                            "Saturday",
                            "00:00:00"});
#line 101
 testRunner.Then("a jornada de trabalho semanal prevista no contrato deverá ser:", ((string)(null)), table17, "Então ");
#line hidden
#line 110
 testRunner.And("o tempo total da jornada de trabalho semanal prevista no contrato deverá ser \'1.1" +
                        "6:00\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="[Abrir Contrato] Trabalhador abre um contrato com uma jornada de trabalho previst" +
            "a de 44 horas semanais (incluindo sábado)")]
        [Xunit.TraitAttribute("FeatureTitle", "Gestão Contratos")]
        [Xunit.TraitAttribute("Description", "[Abrir Contrato] Trabalhador abre um contrato com uma jornada de trabalho previst" +
            "a de 44 horas semanais (incluindo sábado)")]
        [Xunit.TraitAttribute("Category", "secondary")]
        public void AbrirContratoTrabalhadorAbreUmContratoComUmaJornadaDeTrabalhoPrevistaDe44HorasSemanaisIncluindoSabado()
        {
            string[] tagsOfScenario = new string[] {
                    "secondary"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("[Abrir Contrato] Trabalhador abre um contrato com uma jornada de trabalho previst" +
                    "a de 44 horas semanais (incluindo sábado)", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 113
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 114
 testRunner.Given("que existe uma abertura de contrato em andamento", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 115
 testRunner.And("que a jornada de trabalho semanal é de \'Monday\' a \'Friday\' das \'09:00\' às \'18:00\'" +
                        " com \'01:00\' de almoço", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 116
 testRunner.And("que a jornada de trabalho de \'Saturday\' é das \'08:00\' às \'12:00\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 117
 testRunner.But("que não tem jornada de trabalho no \'Sunday\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Mas ");
#line hidden
#line 118
 testRunner.When("o trabalhador abrir um contrato", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
                TechTalk.SpecFlow.Table table18 = new TechTalk.SpecFlow.Table(new string[] {
                            "dia semana",
                            "tempo"});
                table18.AddRow(new string[] {
                            "Sunday",
                            "00:00:00"});
                table18.AddRow(new string[] {
                            "Monday",
                            "08:00:00"});
                table18.AddRow(new string[] {
                            "Tuesday",
                            "08:00:00"});
                table18.AddRow(new string[] {
                            "Wednesday",
                            "08:00:00"});
                table18.AddRow(new string[] {
                            "Thursday",
                            "08:00:00"});
                table18.AddRow(new string[] {
                            "Friday",
                            "08:00:00"});
                table18.AddRow(new string[] {
                            "Saturday",
                            "04:00:00"});
#line 119
 testRunner.Then("a jornada de trabalho semanal prevista no contrato deverá ser:", ((string)(null)), table18, "Então ");
#line hidden
#line 128
 testRunner.And("o tempo total da jornada de trabalho semanal prevista no contrato deverá ser \'1.2" +
                        "0:00\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="[Encerrar Contrato] Trabalhador encerra um contrato")]
        [Xunit.TraitAttribute("FeatureTitle", "Gestão Contratos")]
        [Xunit.TraitAttribute("Description", "[Encerrar Contrato] Trabalhador encerra um contrato")]
        [Xunit.TraitAttribute("Category", "main")]
        [Xunit.TraitAttribute("Category", "wip")]
        public void EncerrarContratoTrabalhadorEncerraUmContrato()
        {
            string[] tagsOfScenario = new string[] {
                    "main",
                    "wip"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("[Encerrar Contrato] Trabalhador encerra um contrato", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 133
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 134
 testRunner.Given("que existe um contrato aberto \'Contrato A\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 135
 testRunner.When("o trabalhador encerrar o contrato", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 136
 testRunner.Then("o contrato deverá ser encerrado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="[Excluir Contrato] Trabalhador exclui um contrato que não era necessário")]
        [Xunit.TraitAttribute("FeatureTitle", "Gestão Contratos")]
        [Xunit.TraitAttribute("Description", "[Excluir Contrato] Trabalhador exclui um contrato que não era necessário")]
        [Xunit.TraitAttribute("Category", "main")]
        public void ExcluirContratoTrabalhadorExcluiUmContratoQueNaoEraNecessario()
        {
            string[] tagsOfScenario = new string[] {
                    "main"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("[Excluir Contrato] Trabalhador exclui um contrato que não era necessário", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 141
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 142
 testRunner.Given("que existe um contrato aberto \'Contrato A\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 143
 testRunner.When("o trabalhador excluir o contrato", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 144
 testRunner.Then("o contrato deverá ser excluído", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="[Excluir Contrato] Trabalhador tenta excluir excluir um contrato com ponto(s) mar" +
            "cado(s)")]
        [Xunit.TraitAttribute("FeatureTitle", "Gestão Contratos")]
        [Xunit.TraitAttribute("Description", "[Excluir Contrato] Trabalhador tenta excluir excluir um contrato com ponto(s) mar" +
            "cado(s)")]
        [Xunit.TraitAttribute("Category", "exception")]
        [Xunit.TraitAttribute("Category", "wip")]
        public void ExcluirContratoTrabalhadorTentaExcluirExcluirUmContratoComPontoSMarcadoS()
        {
            string[] tagsOfScenario = new string[] {
                    "exception",
                    "wip"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("[Excluir Contrato] Trabalhador tenta excluir excluir um contrato com ponto(s) mar" +
                    "cado(s)", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 149
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 150
 testRunner.Given("que existe um contrato aberto \'Contrato C\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 152
 testRunner.When("o trabalhador excluir o contrato", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 153
 testRunner.Then("o contrato não deverá ser excluído", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                GestaoContratosFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                GestaoContratosFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
